name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze || true

      - name: Test
        run: flutter test || true

      - name: Build APK (debug, smoke)
        run: flutter build apk --debug --dart-define=API_BASE=https://api.hamztech.my.id/api
